# Generated by Django 5.0.3 on 2024-03-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0003_alter_book_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='', upload_to='static/images'),
        ),
    ]
