# Generated by Django 5.0.3 on 2024-03-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0004_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='', upload_to='static/images/cover'),
        ),
    ]
